language: python
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install python3.4-dev

install:
    - pip install tox six

before_script: mysql -e 'create database mysqldb_test charset utf8;'
script: TESTDB=travis.cnf tox
