sudo: false
language: python
cache: pip
install:
    - pip install tox

before_script:
    - "mysql --help"
    - "mysql --print-defaults"
    - "mysql -e 'create database mysqldb_test charset utf8mb4;'"
script: TESTDB=travis.cnf tox
