language: python
python:
 - "2.5"
 - "2.6"
 - "2.7"
install: (cd MySQLdb && python setup.py install)
before_script: mysql -e 'create database mysqldb_test charset utf8;'
script: (cd MySQLdb && TESTDB=travis.cnf nosetests)
