contact_links:
  - name: Failed to build
    about: Ask help for build error.
    url: "https://github.com/PyMySQL/mysqlclient/discussions/new?category=build"

  - name: Ask question
    about: Ask other questions.
    url: "https://github.com/PyMySQL/mysqlclient/discussions/new?category=q-a"
